version: "3.8"
volumes:
  build_folder: null
  static_volume: null
  media_volume: null

services:
  frontend:
    build:
      context: ./front
      args:
        API_URL: "*"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    volumes:
      - ./front/:/frontend
      - build_folder:/frontend/build
      - ./front/node_modules/:/frontend/node_modules
    tty: true

  nginx:
    build: ./nginx
    ports:
      - 80:8080
    volumes:
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend

  backend:
    build: ./back
    command: "yarn start"
    ports:
      - "8080:8080"
    volumes:
      - ./back:/backend

  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8282"
    command:
      - "php"
      - "-S"
      - "[::]:8282"
      - "-t"
      - "/var/www/html"
